services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db_results:5432/results_db
      - BENCHMARK_DB_URL=postgresql+asyncpg://root:password@db_bench:5432/postgres
    depends_on:
      - db_results
      - db_bench
    volumes:
      - ./data:/app/data

  db_results:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: results_db
    ports:
      - "5433:5432"
    volumes:
      - results_data:/var/lib/postgresql/data

  db_bench:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
      - bench_data:/var/lib/postgresql/data
      - ./data/bird-interact-full-dumps/init-databases_postgresql.sh:/docker-entrypoint-initdb.d/init-databases_postgresql.sh
      - ./data/bird-interact-full-dumps:/docker-entrypoint-initdb.d/postgre_table_dumps
      - ./data:/app/data_mount

  ai_mock:
    build: ./ai_mock
    ports:
      - "8001:8001"

volumes:
  results_data:
  bench_data:
